### PR TITLE
Change Cint to Clong to handle 64-bit sizes

### LINKED ISSUE #22: 64 bit pointers?
We ran into a case where 64-bit pointers are required, and ZfpCompression is failing with a truncation error. I am wondering why the choice to use 32 bit pointers? Why not use `Clong` instead of `Cint`? Is it possible to switch to 64-bit integers?

### PR DESCRIPTION
**Pull request by jkwashbourne-oss**
Fixes #22

### CODE REVIEW

**Review by milankl — APPROVED** [review]

**Comment by milankl** [comment]
Looks good, do you need this as a new tagged release?

**Comment by jkwashbourne-oss** [comment]
A new release would be great, but no rush. I need to figure out what the branch syntax is here tho `ZfpCompression#patch-1` is not right.

**Comment by jkwashbourne-oss** [comment]
maybe I do need a release ...

**Comment by milankl** [comment]
Your branch is still at [jkwashbourne-oss:patch-1](https://github.com/jkwashbourne-oss/ZfpCompression.jl/tree/patch-1) once I merge it's also in #master

**Comment by jkwashbourne-oss** [comment]
I was trying to do `add ZfpCompression#branch` 

thanks much for the quick help! really appreciate it. just ran into this when we moved to a larger problem with ensembles of size 433,000 x 8001.

**Pull request merged**
