### PR TITLE
ensure compatibility with ZFP 1.0.0

### PR DESCRIPTION
**Pull request by jvo203**
This Pull Request makes sure ZfpCompression.jl works with the new zfp_jll 1.0.0. In particular, the ```ZfpField``` Julia structure has been revised:

- the dimensions now use ```Csize_t```
- the strides use ```Cptrdiff_t```

### CODE REVIEW

**Comment by giordano** [comment]
You must add compat with zfp_jll 1 in the Project file.

**Comment by jvo203** [comment]
Sorry I don't know how to correctly edit the Project.toml file... I mean the package maintainer (not me) knows the correct settings like the new ID for the new ```zfp_jll``` etc. I don't want to break things I am not familiar with.

Personally I submitted the source corrections needed to make ```ZfpCompression.jl``` work with the new ZFP 1.0.0. The rest, i.e. making a new release etc. is the responsibility of the package maintainer.

**Comment by giordano** [comment]
```toml
[compat]
zfp_jll = "1"
julia = "1.3"
```

**Comment by jvo203** [comment]
Thank, have added to the [compat] section on my side. But what about the uuid in the [deps]?

The current setting:
```
[deps]
zfp_jll = "007be453-5351-5f08-b8c7-bf95923b8de2"
```

**Comment by giordano** [comment]
> But what about the uuid in the [deps]?

That one doesn't have to change: it's the identifier of the package in [the registry](https://github.com/JuliaRegistries/General), the package didn't change 🙂

**Comment by jvo203** [comment]
I see... OK, that's done, have just updated the original Pull Request.

**Review by milankl — APPROVED** [review]

**Review by jvo203 — COMMENTED** [review]
Thank you.

**Pull request merged**
